### ISSUE TITLE
login method is dead with RC8.1

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/sdk-javascript#162]
Unable to use the login sdk method with kuzzle RC8.1

`kuzzle_1         | error: 2016-12-26T09:25:07+00:00 [LOG:ERROR]  status=403, message=Login failed, stack=Error
kuzzle_1         |     at ForbiddenError.KuzzleError (/var/app/node_modules/kuzzle-common-objects/lib/errors/kuzzleError.js:17:19)
kuzzle_1         |     at new ForbiddenError (/var/app/node_modules/kuzzle-common-objects/lib/errors/forbiddenError.js:6:15)
kuzzle_1         |     at context.passwordManager.checkPassword.then.result (/var/app/node_modules/kuzzle-plugin-auth-passport-local/lib/passport/strategy.js:14:29)
kuzzle_1         |     at _fulfilled (/var/app/node_modules/q/q.js:834:54)
kuzzle_1         |     at self.promiseDispatch.done (/var/app/node_modules/q/q.js:863:30)
kuzzle_1         |     at Promise.promise.promiseDispatch (/var/app/node_modules/q/q.js:796:13)
kuzzle_1         |     at /var/app/node_modules/q/q.js:556:49
kuzzle_1         |     at runSingle (/var/app/node_modules/q/q.js:137:13)
kuzzle_1         |     at flush (/var/app/node_modules/q/q.js:125:13)
kuzzle_1         |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
kuzzle_1         |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)`

**Comment by AnthonySendra** [comment]
The problem comes from the refactor about moving trigger into the `funnel.processRequest`.
Because of that, the method `createFirstAdmin` in the `cliController` bypass the `trigger` function.

https://github.com/kuzzleio/kuzzle/blob/master/lib/api/controllers/cliController.js#L15

The method `encryptCredentials` attached to the event `security:beforeCreateFirstAdmin` is never called.

**Comment by scottinet** [comment]
Resolved.
