### ISSUE TITLE
[6-dev] add a way to discard pending request

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/sdk-javascript#360]
In case of an statefull application like in Vuejs / React / Electron, we may want to discard long pending request when a user change it's state

## Current Behavior
1. The User go to a page where a search query will fetches a big amount of data
2. The User leave the page before the query complete
3. If the User come back again, which fire a new request even the previous hasn't finished
4. The previous request handler may fire before or after the new one, which will cause an unwanted ugly reload effect

## Expected Behavior
1. The User go to a page where a search query fetches a big amount of data
2. The User leave the page before the query complete
3. At this point, as a developer, we know that the user is leaving so we discard his pending request.
4. If the User come back again, which fire a fresh new request

> notice that if the request need a large amount of computing unit (like map reducing operation, heavy search queries, etc..), it would be nice to have an option to tell to Kuzzle to internally discard the query.

**Comment by Aschen** [comment]
Hi @stafyniaksacha,

Sorry for the long respond time.

It's a real good idea! I just proposed this feature to the team, expect to have some news quickly.

**Comment by xbill82** [comment]
Hello Sacha!
We've been discussing your issue in depth. If we understand properly, you have a page `A` that triggers a request (that takes a lot of time to complete) once mounted, in order to build its UI with the contents of the response.
The problem is
* the user loads page `A`
* `A` triggers the request `R1`
* then the user quits page `A` and loads page `B` (before the request completed, `A` is not destroyed by the framework)
* the user goes back to page `A` (the framework re-uses the same instance)
* `A` triggers another request `R2`
*  `R1` resolves and `A` shows the results
* immediately after, `R2` resolves and `A` shows the results again, which results in an ugly flick to the eyes of the user.

Right?

So, the solution wouldn't be that `A` should avoid triggering `R2` if `R1` has not completed?

**Comment by Yoann-Abbes** [comment]
Close due to inactivity
