### ISSUE TITLE
[Docs - Getting Started] Install :latest on getting-started instead of v7?

### ISSUE THREAD

**Issue by Leodau** [kuzzleio/sdk-javascript#501]
## Expected Behavior
Should _Getting-Started_ like documentation be version-agnostic? 🤔

### Example: _(Non-exhaustive)_
[Getting Started Kuzzle + VueJS](https://github.com/kuzzleio/sdk-javascript/blob/master/doc/7/getting-started/vuejs/standalone/index.md#prepare-your-environment)

## Current Behavior
Documentation tells the users to install specific version of the **sdk, in this case: 7.**
`npm install kuzzle-sdk@7`

## Possible Solution
Replace with:
`npm install kuzze-sdk@latest`

**Comment by Aschen** [comment]
Getting started are not version agnostics because they live on a particular version of the documentation which correspond to a major version of the SDK.

For example this is the v6 version of the Vue.js getting started: https://docs.kuzzle.io/sdk/js/6/getting-started/vuejs/standalone/ (which need to be updated to install the v6 version of the SDK :sweat_smile: )
