### ISSUE TITLE
browser/kuzzle.min.js is outdated

### ISSUE THREAD

**Issue by killerwolf** [kuzzleio/sdk-javascript#6]
seeems like you forgot to update your disted file in /browser

**Comment by scottinet** [comment]
Fixed, for now. I forget it all the time, that's why I've planned to put some kind of automatic update on pull requests this week, probably using Travis. I need to configure a CI job and start writing unit tests for this SDK anyway.

I'll keep this issue open until then, just to keep track of this problem.

**Comment by scottinet** [comment]
And... done. There is now a ``browser`` project branch, automatically updated by Travis when merging into the master branch.
