### ISSUE TITLE
Cannot access request argument with HTTP protocol on GET route

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/sdk-javascript#713]
## Description

`index`, `collection` and other arguments are not present in request input while using the HTTP protocol of the SDK.

I suspect the URL to be incorrectly created by the SDK Http protocol since the generated route is `GET`

### Backend

```js

app.controller.register("efficient", {
  actions: {
    "efficient": {
      handler: async (request: KuzzleRequest) => {
console.log(request.input.args);
if (request.input.args.index === undefined) {
  throw new Error('No index');
}
      }
    }
  }
})
```

## Client (SDK)

```js
import { Kuzzle, Http } from 'kuzzle-sdk';

const kuzzle = new Kuzzle(new Http('localhost'));

await kuzzle.query({
    controller: 'efficient',
    action: 'efficient',
    index: "index",
    collection: "collection",
    body: { hey: "hey" },
});
```

**Comment by alexandrebouthinon** [comment]
I successfully reproduce this but this is only the case when custom arguments are named:
- collection
- index
- meta
- headers
- controller
- action
- requestId

This is because they are present in a ["boilerplate" payload](https://github.com/kuzzleio/sdk-javascript/blob/6aaf6e1630187a885191fd57123b7b25d946fb40/src/protocols/Http.ts#L249) used to compare with the given user request and forge the final request to send:
https://github.com/kuzzleio/sdk-javascript/blob/6aaf6e1630187a885191fd57123b7b25d946fb40/src/protocols/Http.ts#L264-L283

I made a patch [here](https://github.com/kuzzleio/sdk-javascript/pull/716). I find it quite dirty but at the same time I have the impression that we don't have much choice to manage this edge case. Your review and suggestions are welcomed 😃

**Comment by Aschen** [comment]
@alexandrebouthinon I saw your fix and it seems good to me :+1: 

True to say this part is already dirty and there is not much to do to make it any cleaner :see_no_evil: So if there is tests then it's ok at least
